-- SỬ DỤNG ĐỂ VẼ dbdiagram:

CREATE TABLE booktour (
	BookTourID INT(10) NOT NULL AUTO_INCREMENT,
	TourID INT(10) NOT NULL,
	MemberID INT(10) NULL DEFAULT NULL,
	AnonymousBookTour VARCHAR(100) NOT NULL ,
	AnonymousEmail VARCHAR(100) NOT NULL ,
	AnonymousAddress VARCHAR(2000) NOT NULL ,
	AnonymousPhone VARCHAR(15) NOT NULL ,
	Status VARCHAR(10) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (BookTourID)
);


CREATE TABLE itemlibrary (
	ItemLibraryID INT(10) NOT NULL AUTO_INCREMENT,
	LibraryID INT(10) NULL DEFAULT NULL,
	Title VARCHAR(1000) NULL DEFAULT NULL,
	File VARCHAR(45) NULL DEFAULT NULL,
	Description LONGTEXT NULL DEFAULT NULL,
	Flag VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (ItemLibraryID)
);


CREATE TABLE library (
	LibraryID INT(10) NOT NULL AUTO_INCREMENT,
	LibraryName VARCHAR(1000) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (LibraryID)
);


CREATE TABLE locationandservice (
	LocationAndServiceID INT(10) NOT NULL AUTO_INCREMENT,
	MountaineeringID INT(10) NOT NULL,
	ServiceID INT(10) NOT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (LocationAndServiceID)
);


CREATE TABLE member (
	MemberID INT(10) NOT NULL AUTO_INCREMENT,
	MemberName VARCHAR(45) NOT NULL ,
	Password VARCHAR(45) NOT NULL ,
	Role VARCHAR(45) NULL DEFAULT NULL ,
	Firstname VARCHAR(15) NOT NULL ,
	Middlename VARCHAR(15) NOT NULL ,
	Lastname VARCHAR(15) NOT NULL ,
	Birthday DATETIME NOT NULL,
	Sex VARCHAR(10) NOT NULL ,
	Telephone VARCHAR(20) NOT NULL ,
	Email VARCHAR(500) NOT NULL ,
	Status VARCHAR(45) NULL DEFAULT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (MemberID)
);


CREATE TABLE mountaineering (
	MountaineeringID INT(10) NOT NULL AUTO_INCREMENT,
	LocationX VARCHAR(100) NOT NULL ,
	LocationY VARCHAR(100) NOT NULL ,
	MountainName VARCHAR(1000) NOT NULL ,
	Level VARCHAR(20) NOT NULL ,
	Banner VARCHAR(2000) NOT NULL ,
	Type INT(10) NOT NULL,
	Sheltering VARCHAR(1000) NOT NULL ,
	Techniques VARCHAR(1000) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (MountaineeringID)
);


CREATE TABLE news (
	NewsID INT(10) NOT NULL AUTO_INCREMENT,
	CategoryID INT(10) NOT NULL,
	Title VARCHAR(1000) NOT NULL,
	Leadcontent VARCHAR(3000) NULL DEFAULT NULL,
	Content LONGTEXT NOT NULL,
	AvatarNews VARCHAR(1000) NOT NULL,
	Author VARCHAR(45) NOT NULL,
	Description LONGTEXT NULL DEFAULT NULL,
	Flag VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (NewsID) 
);


CREATE TABLE service (
	ServiceID INT(10) NOT NULL AUTO_INCREMENT,
	ServiceName VARCHAR(1000) NOT NULL,
	Price DECIMAL(10,0) NOT NULL,
	VAT INT(10) NOT NULL,
	Description LONGTEXT NULL DEFAULT NULL,
	Flag VARCHAR(1) NULL DEFAULT NULL,
	Sale INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (ServiceID) 
);


CREATE TABLE tour (
	TourID INT(10) NOT NULL AUTO_INCREMENT,
	CategoryTourID INT(10) NOT NULL,
	TourName VARCHAR(1000) NOT NULL ,
	TimeStart DATETIME NOT NULL,
	TimeLimit VARCHAR(100) NOT NULL ,
	TourPrice DECIMAL(10,0) NOT NULL,
	TourSale DECIMAL(10,0) NULL DEFAULT NULL,
	Location VARCHAR(1000) NOT NULL ,
	AvatarTour VARCHAR(2000) NOT NULL ,
	Status VARCHAR(20) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (TourID) 
);


CREATE TABLE usersystem (
	UserSystemID INT(10) NOT NULL AUTO_INCREMENT,
	UserName VARCHAR(100) NOT NULL ,
	Password VARCHAR(500) NOT NULL ,
	Role VARCHAR(500) NULL DEFAULT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Status VARCHAR(20) NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (UserSystemID) 
);


CREATE TABLE contact (
	contactID INT(10) NOT NULL AUTO_INCREMENT,
	MemberID INT(10) NOT NULL,
	fullname VARCHAR(500) NOT NULL ,
	address VARCHAR(1000) NOT NULL ,
	email VARCHAR(100) NOT NULL ,
	telephone VARCHAR(15) NOT NULL ,
	message LONGTEXT NOT NULL ,
	description LONGTEXT NULL DEFAULT NULL ,
	flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (contactID) 
);


CREATE TABLE category (
	CategoryID INT(10) NOT NULL AUTO_INCREMENT,
	CategoryName VARCHAR(1000) NOT NULL ,
	ParentID INT(10) NULL DEFAULT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (CategoryID) 
);


CREATE TABLE categorytour (
	CategoryTourID INT(10) NOT NULL AUTO_INCREMENT,
	CategoryTourName VARCHAR(1000) NOT NULL ,
	Status INT(10) NULL DEFAULT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (CategoryTourID) 
);

